name: Build Goo Engine Windows
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      # BƯỚC QUAN TRỌNG: Xóa các phần mềm thừa trên máy chủ GitHub để lấy 20GB+ dung lượng
      - name: Giải phóng dung lượng ổ đĩa
        run: |
          Get-ChildItem -Path "C:\Program Files\dotnet" -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
          Get-ChildItem -Path "C:\Android" -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue

      - name: Tải thư viện bổ trợ (SVN)
        run: |
          # Chạy lệnh update để lấy lib
          ./make.bat update

      - name: Tiến hành Build
        run: |
          # Dùng lệnh này để build bản rút gọn, tránh tràn bộ nhớ
          ./make.bat release
