name: Build Goo Engine
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cleanup Disk Space
        run: |
          # Xóa bớt dữ liệu thừa trên server để lấy chỗ cho bộ thư viện 15GB
          Remove-Item -Recurse -Force "C:\Program Files\dotnet"
          Remove-Item -Recurse -Force "C:\Android"

      - name: Install Libraries
        run: ./make.bat update

      - name: Compile Goo Engine
        run: ./make.bat release

      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: GooEngine-Windows
          path: ../build_windows_Full_x64_vc17_Release/bin/Release/
