name: Build Goo Engine
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Đảm bảo có Python để script không báo lỗi "Python not found"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cleanup Disk Space
        run: |
          Remove-Item -Recurse -Force "C:\Program Files\dotnet" -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force "C:\Android" -ErrorAction SilentlyContinue

      # Sử dụng lệnh "echo y |" để tự động trả lời Yes cho câu hỏi tải thư viện
      - name: Install Libraries
        run: echo y | ./make.bat update

      - name: Compile Goo Engine
        run: ./make.bat release

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: GooEngine-Windows-Final
          path: ../build_windows_Full_x64_vc17_Release/bin/Release/
